language: python
python:
  - "2.7"
before_script:
  - pip install coverage pep8 --use-mirrors
install:
  - pip install -e . --use-mirrors
script:
  - pep8 --repeat src/
  - nosetests --with-coverage -v test/*.py
notifications:
  email: false
